### PR TITLE
Allow multiple matchers for NetObserv multi-tenancy (NETOBSERV-171)

### PR DESCRIPTION
**Pull request by jotak**
JIRA: https://issues.redhat.com/browse/NETOBSERV-171

- Config "opa.matcher" now accepts multiple values
- Add config argument "--opa.matchers-logical-op" for logical operation to apply when there are several matchers
- Update matcher logic to allow above changes
- Update tests
- Move some matcher logic from package `handler` to `config`, as the new related `Matcher` struct has to be imported from `authorizer` package.

Related PRs:
- https://github.com/observatorium/api/pull/440
- https://github.com/grafana/loki/pull/8192

### CODE REVIEW

**Comment by periklis** [comment]
@jotak This looks great looking at the code. Can you provide some examples on how multiple label matcher look like? Currently we use the matcher facility to return something like this:
```
kubernetes_namespace_name=~"namespaceA|namespaceB"
```

**Comment by jotak** [comment]
> @jotak This looks great looking at the code. Can you provide some examples on how multiple label matcher look like? Currently we use the matcher facility to return something like this:
> 
> ```
> kubernetes_namespace_name=~"namespaceA|namespaceB"
> ```

I need to double-check, but the intent is to leave everything unchanged, unless several matchers are provided.
BTW I found that the API in `ast.go` already accepted several matchers, even if `opa.matcher` didn't support it. So the query injection would already be capable of writing:

```
{nskey1=~"namespaceA|namespaceB",nskey2=~"namespaceA|namespaceB"}
```
which corresponds to the logical AND.

Now as you know, I'm interested in the logical OR, so that's where I still need to work on


> 
> In addition can you elaborate if you need to list some extra resources beyond namespaces from the APIserver? Background of this question is that we use caching for namespaces to keep the communication between opa-openshift to the APIServer as minimal as possible.

**Review by periklis — COMMENTED** [review]
In general looks good to me. I will add my approve once I have tested this in companion with observatorium-api on our Loki Operator release branches.

**Review by periklis — APPROVED** [review]
Approving this PR as is right now. Waiting for merge until I get a green light from OpenShift Logging release manager as per main branch being used for multiple releases right now (i.e. OpenShift Logging 5.5, 5.6 and upcoming 5.7).

**Pull request merged**
